controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    skid_cont:
      type: diff_drive_controller/DiffDriveController

    position_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


skid_cont:
  ros__parameters:
    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['front_left_wheel_joint', 'rear_left_wheel_joint']
    right_wheel_names: ['front_right_wheel_joint', 'rear_right_wheel_joint']

    wheel_separation: 2.0
    wheel_radius: 0.55

    use_stamped_vel: false

    # open_loop: false    

    # wheels_per_side: 2
    # wheel_separation_multiplier: 1
    # left_wheel_radius_multiplier: 1
    # right_wheel_radius_multiplier: 1

    # odom_frame_id: x
    # pose_covariance_diagonal: x
    # twist_covariance_diagonal: x
    # open_loop: x
    # enable_odom_tf: x

    # cmd_vel_timeout: x
    # publish_limited_velocity: x
    # velocity_rolling_window_size: x
    

    # linear.x.has_velocity_limits: false
    # linear.x.has_acceleration_limits: false
    # linear.x.has_jerk_limits: false
    # linear.x.max_velocity: NAN
    # linear.x.min_velocity: NAN
    # linear.x.max_acceleration: NAN
    # linear.x.min_acceleration: NAN
    # linear.x.max_jerk: NAN
    # linear.x.min_jerk: NAN

    # angular.z.has_velocity_limits: false
    # angular.z.has_acceleration_limits: false
    # angular.z.has_jerk_limits: false
    # angular.z.max_velocity: NAN
    # angular.z.min_velocity: NAN
    # angular.z.max_acceleration: NAN
    # angular.z.min_acceleration: NAN
    # angular.z.max_jerk: NAN
    # angular.z.min_jerk: NAN

position_trajectory_controller:
  ros__parameters:
    joints:
      - mnp_base_joint      
      - mnp_first_joint
      - mnp_second_joint
      - mnp_third_joint

    command_interfaces:
      - position

    state_interfaces:
      - position

    state_publish_rate: 100.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

      
# joint_traj_cont:
#   ros__parameters:
#     joints:
#       - mnp_first_joint
#       # - mnp_second_joint
#       # - mnp_third_joint
#     interface_name: position
#     command_interfaces:
#       - position

#     state_interfaces:
#       - position
#       - velocity

#     action_monitor_rate: 50.0

#     allow_partial_joints_goal: true
#     open_loop_control: true
#     constraints:
#       stopped_velocity_tolerance: 0.01
#       goal_time: 0.05
      # mnp_first_joint:
      #   trajectory: 0.05
      #   goal: 0.03


# joint_broad:
#   ros__parameters:
